### ISSUE TITLE
Compound XOR operator

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#101]
The Lua XOR operator (`~`) does not seem to have a compound counterpart in Pluto.

**Comment by well-in-that-case** [comment]
It'd collide with the inequality operator.

**Comment by Sainan** [comment]
Even if not exactly `~=`, e.g. what about `x=`? But I don't know how that would out variables named `x`.

**Comment by well-in-that-case** [comment]
In my opinion, too ambiguous.
