### ISSUE TITLE
Break-by-default `switch` statement

### ISSUE THREAD

**Issue by Apis035** [PlutoLang/Pluto#1028]
```lua
switch op do
    case 'fad' -> scene:fade(p1, p2)
    case 'wai' -> scene:wait(p1)
    case 'say' -> actor:say(p1)
    case 'mov':
        actor:setanim("walk")
        actor:setpos(p1, p2)
        break
    default -> error("Unknown command: " .. op)
end
```

- `case` opened by colon will fallthrough.
- `case` opened by arrow will have implicit `break` at the end of the case.
- Mixed `switch` with arrow and colon case will have the colon case break at the next arrow case or until `break` keyword.

Just an idea, there could be an edge case on the semantics.

Edit: Cleaned post

<details>
<summary>Detail</summary>

e.g.

```lua
local commands = {
    {'fad', 'in', 2},
    {'mov', 100, 20},
    {'wai', '2'},
    {'say', 'Where is this?'},
    {'fad', 'out', 3},
}

commands:foreach(execute)
```

`execute` function:
```lua
local [op, p1, p2] = command

switch op do
    case 'fad': scene:fade(p1, p2) break
    case 'wai': scene:wait(p1) break
    case 'say': actor:say(p1) break
    case 'mov':
        actor:setanim("walk")
        actor:setpos(p1, p2)
        break
    default:
        error("Unknown command: " .. op)
        break
end
```

The **switch statement** which contains only 1-2 statement on each case could be tidied up by using **switch expression**, removing the need to write `break` to avoid fallthrough.

```lua
_ = switch op do
    case 'fad' -> scene:fade(p1, p2)
    case 'wai' -> scene:wait(p1)
    case 'say' -> actor:say(p1)
    case 'mov' -> actor:setpos(p1, p2) -- can only put 1 statement... (expression)
    default -> error("Unknown command: " .. op)
end
```

How about borrowing the arrow syntax to **switch statement**? If a case is opened by **colon**, then it is a fallthrough case. If opened by **arrow**, then it is a break-by-default case.

Can't think of a better, shorter example.

</details>

**Comment by Sainan** [comment]
I get the appeal, but in case of a switch expression, the entire switch block produces a result. In the case of a switch block, if there was a result value, any resulting value would just be discarded. So, it's not only syntactically cursed, but also semantically cursed.

**Comment by Apis035** [comment]
I'm writing that at 1 AM, I don't know what I'm doing.

Better idea:
```lua
switch i do
case 1:
    foo()
    -- break
case 2:
    bar()
    fallthrough -- no break
case 3:
    baz()
    -- break
end
```
Introduce `fallthrough` keyword. Although I'm unsure how to signal the switch as break-by-default switch.

Identical to normal switch but inverted. Have implicit `break` at the end of the case and uses `fallthrough` to make it fall to next case.

**Comment by Sainan** [comment]
Cool, only a totally breaking change.

**Comment by Sainan** [comment]
We already have a warning for unannotated fallthrough, that oughta be enough.

![image](https://github.com/user-attachments/assets/fde2a895-1754-4374-a13d-9ad4d9819df9)

**Comment by Apis035** [comment]
Yeah, the warning is good enough. I could just use the `_ = switch x do` workaround for single statement cases.

Closing this.
