### ISSUE TITLE
Relative require

### ISSUE THREAD

**Issue by asumbek** [PlutoLang/Pluto#1052]
```lua
local module = require("./foo/bar/module.lua")

package.basename -- The "base" path of the module
package.dirname -- The directory where the module was placed
```

**Comment by Sainan** [comment]
`dofile`.

**Comment by asumbek** [comment]
`dofile` only do relative load based on CWD, while relative require do relative load based on the module's directory.

For example:
```lua
-- main.lua
dofile "./foo/bar.lua"
```
```lua
-- foo/bar.lua
dofile "./helpers.lua" -- Will fail because there's no `$PWD/helpers.lua`, while the expected file is in `$PWD/foo/helpers.lua`
```

For reference: [Luvit `require`](https://github.com/luvit/luvit/blob/master/deps/require.lua)

**Comment by Sainan** [comment]
If you want it relative to the current file, I think `debug.getinfo(1).source:sub(2)` should do the trick.
