### ISSUE TITLE
f-strings

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#119]
I think it would be possible to detect this kind of function call in the paser:
```Lua
f"Hello, {subject}!"
```
or, for compatibility:
```Lua
pluto_f"Hello, {subject}!"
```
and then generate an expression that's just getting the variables (local or global) and concating it into the final string.

**Comment by well-in-that-case** [comment]
It's possible to detect these sorts of things inside the lexer and splice the string into multiple parts, which allows us to pretend concatenation happens around the variable. It's faster, but also extremely tedious to implement (source: I've tried, a lot)
