### ISSUE TITLE
Brackets as alternative block syntax

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#132]
```Lua
local a = 3
if a == 3 {
    print("a is 3!")
}
```

**Comment by well-in-that-case** [comment]
I don't think there's a way to avoid a major syntactic ambiguity in this instance:
```lua
if a == b {
    print("a == b")
}
```
`b {}` is a valid function call.

**Comment by Sainan** [comment]
Hmm. I suppose `if (a == b) { ... }` does not have any ambiguity. But I don't know how useful this would even be.
