### ISSUE TITLE
Raw String Literals

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#134]
Raw String Literals aka. heredoc can be useful for conveniently coding in multi-line string literals or Windows file paths.

Example syntax:
```LUA
print(R"(Hello \ World!)")
```

**Comment by well-in-that-case** [comment]
The multi-line string syntax `[[hello world]]` already provides raw string stuff, and I think that addresses heredoc but I might've misunderstood.

**Comment by Sainan** [comment]
Wait, this is already a lua feature?!

**Comment by well-in-that-case** [comment]
Yeah. I don't really like how you need to do a multi-line string for a raw literal, but it's there nonetheless.
