### ISSUE TITLE
"foreach" keyword

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#135]
This might be the most useless suggestion ever, but I'd much rather type:
```Lua
foreach v in t do
    -- ...
end
```
than:
```Lua
for _, v in t do
    -- ...
end
```
or perhaps an alternative syntax that might be possible due to the improved lexer:
```Lua
for t as v do
    -- ...
end
```

**Comment by well-in-that-case** [comment]
Maybe keyword, I wonder if this function would be of any use too.
https://www.lua.org/source/5.1/ltablib.c.html#foreach
