### ISSUE TITLE
"Universal" variations of functions like tostring, string.format, etc.

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#198]
Currently, these functions rely on the locale, which is fine for console output and such, but when people want to export to/import from files, this can be quite bothersome (if they know it's an issue at all). So, I propose we provide alternative functions that switch to `en-US` locale, do the thing, then switch back. I was thinking `io.tostring` instead of `tostring`, but maybe we could just consistently prefix these functions, e.g. `utostring`, `string.uformat`

**Comment by well-in-that-case** [comment]
The prefixes are more aesthetically pleasing, imo.
