### ISSUE TITLE
Indexing / At Enum

### ISSUE THREAD

**Issue by Ayimforgoroldacc** [PlutoLang/Pluto#242]
enum MyEnum begin
    OPTION_1,
    OPTION_2,
    OPTION_3
end

MyEnum:at(1) --Value at index 1

Being able to index a Enum like this maybe would be nice

**Comment by Sainan** [comment]
What would be the use-case for this?

**Comment by Ayimforgoroldacc** [comment]
I have a couple "comboboxes" which I kinda have linked to a list right now and would like to replace it with a enum by being able to index the Enum I can implement that

**Comment by Sainan** [comment]
Could you provide an example of the code that you would like to be functional? Your example is a bit too contrived and does not provide enough information on what it's supposed to do and what restrictions the implementation needs to fit.

**Comment by Ayimforgoroldacc** [comment]
(Code is written out of my head / example-ified dont mind syntax errors if there are any)

Well for example in my code I have

```
enum myEnum begin
    OPTION_1,
    OPTION_2,
    OPTION_3 = 9
end
```

and another part of the code where I have this:

```
local testList = myEnum:values()

comboBox(myEnum::names(), ComboboxCallback)

ComboboxCallback(index, value)
	id = testList[index]
        ...
end
```


what I'd like to just be able to do is


```
enum myEnum begin
    OPTION_1,
    OPTION_2,
    OPTION_3 = 9
end

comboBox(myEnum::names(), ComboboxCallback)

ComboboxCallback(index, value)
	id = myEnum:at(index)
        ...
end
```

**Comment by Sainan** [comment]
I figured as much. Unfortunately, the information needed to do that is not available at runtime. Your best bet is using an anonymous function for the callback and wrapping that in an abstraction that takes the result of enum vkmap or kvmap.
