### ISSUE TITLE
Optional Bracket Block closing

### ISSUE THREAD

**Issue by Ayimforgoroldacc** [PlutoLang/Pluto#255]
honestly have no good title and this is just a kinda cool thing to have not very useful

examples will have to do

```
local function returnGivenValue(value) {
    return value
}


if returnGivenValue(true) {
    
}

```

**Comment by Sainan** [comment]
Ambiguous to parse due to table constructor. Besides, it's Lua. You simply use `then` or `do` and index your ~~arrays~~ tables starting at 1. Be glad it's not Python where your indentation determines the scope. 🙂

**Comment by Ayimforgoroldacc** [comment]
alright alright... was worth a shot :)
