### ISSUE TITLE
Table # operator is incorrect after 2+ inserts

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#29]
```Lua
t = {}
table.insert(t, "Hello")
table.insert(t, "World")
print(#t)
```
prints 1

**Comment by well-in-that-case** [comment]
Investigating. Feeling like this may need a change to the insert function. Iirc, cache resetting is only being performed directly in the virtual machine. (Which would explain this)

**Comment by well-in-that-case** [comment]
Potentially fixed here:
https://github.com/well-in-that-case/Pluto/commit/422a5c6b4bf3dabe87a4016feb8f6bb426464d58

Edit: Let me know in the meantime if it reoccurs, otherwise I'll close this ticket in a little while.

**Comment by Sainan** [comment]
Yeah, that fixed it.
