### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Ayimforgoroldacc** [PlutoLang/Pluto#299]
doestn error:

```
class Human
    function __construct(name)
        self.name = name
    end
end

local john = new Human("John")
print(john.name)

```
errors:
```
class Human
    function __construct(name)
        self.name = name
    end
end

print(new Human("John").name)
```

**Comment by Ayimforgoroldacc** [comment]
> errors:
> 
> ```
> class Human
>     function __construct(name)
>         self.name = name
>     end
> end
> 
> print(new Human("John").name)
> ```


pluto: syntax error: tmp.pluto:7: ')' expected (got '.')
    7 | print(new Human("John").name) -- John
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ here: this is invalid syntax.

**Comment by Ayimforgoroldacc** [comment]
I see this probably isnt a bug but something not implemented yet but this kinda syntax

```
class Human
    function __construct(name)
        self.name = name
    end
    
    function sayHello()
        local name = self.name
        print($"Hello world and {name}")   
    end
end

new Human("John"):sayHello()
```
would be pretty nice to have

**Comment by Sainan** [comment]
You can do this:
```Lua
(new Human("John")):sayHello()
```
I will track your suggestion in #300.
