### ISSUE TITLE
String interpolation bug

### ISSUE THREAD

**Issue by 4d72526f626f74** [PlutoLang/Pluto#324]
![string_interpolation](https://github.com/PlutoLang/Pluto/assets/92627754/fadfa42f-4f42-4199-bdaf-35063e66a835)

Using single quotes instead of double quotes with the latest version of Pluto results in the following error

**Comment by well-in-that-case** [comment]
https://github.com/PlutoLang/Pluto/issues/320#issue-1812375929

Will be fixed in 0.7.1.
