### ISSUE TITLE
String interp failing with regex matching

### ISSUE THREAD

**Issue by stagnate6628** [PlutoLang/Pluto#331]
```
--[[
[7/23/2023 1:30:07 PM] test.lua: syntax error: [string "test.lua"]:1: unfinished string expression near <string>
    1 | local path = 'c:\my\path\to\file\some\where\else\log.txt'
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ here
]]

local path = 'c:\\my\\path\\to\\file\\some\\where\\else\\log.txt'
print(path:match('[^\\/]*$'))--log.txt
print($'{path:match('[^\\/]*$')}')--fails
```

While this issue is not my biggest concern currently (nor do I think it is a big issue in general), I would appreciate if this gets looked at. For context, I am also doing string interp with the file name but it is not shown in the repo; I also could just use vanilla string concat instead or splice the string as possible solutions. Didn't test with other regexes. I don't know if this issue is because of me not being able to properly escape the string...🥴

**Comment by Sainan** [comment]
The lexer is not exactly wrong to say that your string is unfinished, because you have a terminating `'` before the `}`. Of course, your intend was to make nested strings, but I'm really not sure if that should be allowed.
