### ISSUE TITLE
'!' as an alias for "not"

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#340]
Instead of:
```Lua
local b = false
if not b then
    print("It's false!")
end
```
Being able to do:
```Lua
local b = false
if !b then
    print("It's false!")
end
```

---

More generally, maybe "Shorthands for common logical operations":
- `!` -> `not`
- `&&` -> `and`
- `||` -> `or`

**Comment by stagnate6628** [comment]
Are other aliases such as `&&` / `||` up for this addition as well?

**Comment by well-in-that-case** [comment]
> Are other aliases such as && / || up for this addition as well?

Yes, those will be considered.

**Comment by Sainan** [comment]
`||` is problematic because `|| ->` could be the start of a lambda that doesn't take any parameters.
