### ISSUE TITLE
Standard Library: Vector3

### ISSUE THREAD

**Issue by well-in-that-case** [PlutoLang/Pluto#388]
Lua being so popular with games? Standard library stuff for this math would be really helpful. Could consider Vector2 too.

**Comment by Sainan** [comment]
Matrix and Quaternion, too. A lot of things possible here with Soup. Should we just force Soup linkage at this point or have code duplicated?

**Comment by well-in-that-case** [comment]
> Matrix and Quaternion, too. A lot of things possible here with Soup. Should we just force Soup linkage at this point or have code duplicated?

Soup has a ton of stuff I'd love to get into Pluto. If you mean our vendor approach by "code duplicated", I definitely like it because of how easy it makes compiling with Soup. Esp. for beginners, but linkage may be the way to go at least for the future as we implement more and more of Soup.

**Comment by Sainan** [comment]
No, the current vendor approach is fine since it's managable, but I'm more trying to avoid instances like `ljson` where the code from Soup Lua Bindings was just duplicated without a clear "chain of custody" so to say.
