### ISSUE TITLE
Class initialization via 'new' fails in precompiled bytecode chunks

### ISSUE THREAD

**Issue by well-in-that-case** [PlutoLang/Pluto#393]
```
pluto: plutoc.out: bad binary format (integer overflow)
```
```lua
local class A
end

new A()
```
Setting `LINE_INJECTED` to 0 removes the error and passes the 0.8.0 test suite. (not a valid line number, but still unsigned-compatible :P)

I am curious, why was LINE_INJECTED `-1886153070` in the first place?

**Comment by Sainan** [comment]
It's just a magic number, derived from the string 'plin' for "Pluto Injected". This just allows us to differentiate between injected and non-injected code.
