### ISSUE TITLE
Infinite loop prevention ignores "repeat until"

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#40]
The following code will run forever, even with ILP enabled:
```LUA
repeat until false
```

**Comment by well-in-that-case** [comment]
Interesting. Reviewed the bytecode of the repeat until loop and nothing obvious stands out, there's still a repeating backward jump. Perhaps something with the TEST opcode?

**Comment by well-in-that-case** [comment]
Appears OP_TEST manually jumps backwards without OP_JMP opcode, adding the same check into OP_TEST or hooking docondjump should fix it. However, be weary for false positives. TEST is the universal condition thingy.
