### ISSUE TITLE
Standard Library: io.last_write_time

### ISSUE THREAD

**Issue by aaronlink127** [PlutoLang/Pluto#413]
suggestion for a standard io function, could possibly be implemented via std::filesystem::last_write_time

**Comment by well-in-that-case** [comment]
How funny, I literally had a function named `touch` (yes, using last_write_time) written out like 12 hours ago for this but decided it wasn't needed. Now that has changed though.

**Comment by Sainan** [comment]
He probably means a getter, not a setter.

**Comment by Sainan** [comment]
But, if we want to have both a getter and a setter, should we use `io.last_write_time` for both similiar to C++ (one takes an argument and the other doesn't), or `io.get_last_write_time` and `io.set_last_write_time`?

**Comment by Sainan** [comment]
But, if we want to have both a getter and a setter, should we use `io.last_write_time` for both similiar to C++ (one takes an argument and the other doesn't), or `io.get_last_write_time` and `io.set_last_write_time`?

**Comment by well-in-that-case** [comment]
The former. An approach similar to `io.currentdir` would be ideal imo, where it's a getter or setter depending if there's an argument passed. I think this should be named `io.touch` since that's the standard terminology for this type of I/O operation + it rolls off the tongue.

**Comment by Sainan** [comment]
`touch` is the name of the _set_ operation, more specifically, the operation of setting the file time to the current time. It also implies creating the file if it doesn't exist.

**Comment by Sainan** [comment]
Or we just name it like my beloved PHP: `filemtime` for the getter, `touch` for the setter. (Terrible names, imo, lol.)

- https://www.php.net/manual/en/function.filemtime.php
- https://www.php.net/manual/en/function.touch.php

**Comment by well-in-that-case** [comment]
This could possibly be lumped in with a greater-scoped `io.attributes` (or something like that) which would return a table of any interesting file attributes (i.e, permissions), then could contain a field for last modification timestamp, and a cfunction for setting it. Some metatable fuckery may allow both `f.timestamp` and `f.timestamp = os.millis()` to behave as expected.
