### ISSUE TITLE
Attempt to modify a frozen table error shows wrong line

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#42]
```LUA
table.freeze(_G)
_G.string = {}
```
This code will produce the following error:
> [string "table.freeze(_G)..."]:1: attempt to modify frozen table.

Note how it indicates line 1 even tho the attempt to modify is on line 2.

More specifically, it will show whichever non-empty line came before the actual infringing line.

**Comment by well-in-that-case** [comment]
Not sure how I can address this in an elegant manner, the virtual machine simply thinks that this is the first line. The error does not happen with other things, so I suppose I can try and encode special behavior for these errors. I'll keep looking into it.

**Comment by well-in-that-case** [comment]
Found the issue, outdated program counters whenever luaG_runerror is called, it's a bug with Lua itself. Fix soon.
