### ISSUE TITLE
"Continue X" & "Break X" syntax for manipulating enclosed loops.

### ISSUE THREAD

**Issue by well-in-that-case** [PlutoLang/Pluto#45]
Inspiring from PHP, `continue 1` would skip not the current loop, but the first enclosing loop above this one. For example:
```lua
for i = 1, 10 do -- Loop 1.
  for i = 1, 5 do -- Loop 2.
    ...
    continue 1 -- This would skip 1 iteration of Loop 1.
    break 1 -- This would break out of Loop 1.
  end
end
```
This should be fairly simple to implement by accessing the `BlockCnt` chain of each `FuncState`, and checking the `isloop` field appropriately. We can simply continue searching the linked list X many times, where X = the numeric argument after the keyword to find our intended loop. This is exactly how `continue` works, but it'll look backwards indefinitely and stop at the first loop.

**Comment by Sainan** [comment]
In PHP, `continue 1;` does the same as `continue;`, `continue 2;` etc. would break out of enclosing loops.

**Comment by well-in-that-case** [comment]
```c
static void continuestat (LexState *ls) {
  FuncState *fs = ls->fs;
  BlockCnt *bl = fs->bl;
  int upval = 0;
  luaX_next(ls); /* skip TK_CONTINUE */
  int backwards = 1;
  if (ls->t.token == TK_INT) {
    backwards = ls->t.seminfo.i;
    luaX_next(ls);
  }
  while (bl) {
    if (!bl->isloop) { /* not a loop, continue search */
      upval |= bl->upval; /* amend upvalues for closing. */
      bl = bl->previous; /* jump back current blocks to find the loop */
    }
    else { /* found a loop */
      if (--backwards == 0) { /* this is our loop */
        break;
      }
      else { /* continue search */
        upval |= bl->upval;
        bl = bl->previous;
      }
    };
  }
  if (bl) {
    if (upval) luaK_codeABC(fs, OP_CLOSE, bl->nactvar, 0, 0); /* close upvalues */
    luaK_code(fs, CREATE_sJ(OP_JMP, (bl->scopeend + OFFSET_sJ + 4), false));
  }
  else error_expected(ls, TK_CONTINUE);
}
```
Made these modifications in an attempt. Says "attempt to perform arithmetic on number", yeah, fun error. Probably an incorrect jump somewhere.

**Comment by well-in-that-case** [comment]
`continue N` syntax has been successfully implemented, help wanted for `break N`
