### ISSUE TITLE
io.contents

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#468]
As a snappier way of reading and writing files without having to worry about managing a file handle.

**Comment by well-in-that-case** [comment]
`io.read` could support a string path which would create a temporary file stream

**Comment by Sainan** [comment]
> `io.read` could support a string path which would create a temporary file stream

I'm not sure if that's the best idea because `io.read(string)` is already used in Lua to read from STDIN with a given pattern.
