### ISSUE TITLE
string.trim, string.ltrim, string.rtim

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#469]
We can probably just copy what PHP did for this:
- https://www.php.net/manual/en/function.trim.php
- https://www.php.net/manual/en/function.ltrim.php
- https://www.php.net/manual/en/function.rtrim.php

It's not impossible to do already in Lua, but it's a bit clunky, e.g. rtrim:
```Lua
local function rtrim(s)
  return s:match("^(.-)%s*$")
end
```

**Comment by well-in-that-case** [comment]
We already have `string.strip`

**Comment by Sainan** [comment]
Fair, that seems to be more or less the same idea, except Python... We should copy PHP's default characters for this, tho. Seems weird having to specify.
