### ISSUE TITLE
[Request] OOP Structures, Syntactic Sugar

### ISSUE THREAD

**Issue by Frityet** [PlutoLang/Pluto#48]
Currently in lua, there is quite a bit of boilerplate code for creating "structs" or "classes" for OOP, and the way it is done is hard to get done "properly" and soundly

```lua
---@class Foo
local Foo = {
	name = "",
	id = 0
}
setmetatable(Foo, Foo)
Foo.__index = Foo

function Foo:new(name, id)
	---@type Foo
	local o = {}
	setmetatable(o, self)

	o.name = name
	o.id = id

	return o
end

function Foo:print()
	print("My name is " .. self.name .. " and my id is " .. self.id)
end

return Foo
``` 

Having this abstracted away would offer usability and readability improvements.

(Some syntax I thought up):
```lua
local struct Foo = {
	name;
	id;

	function create(name, id)
		self.name = name
		self.id = id
	end

	function print()
		print("My name is " .. self.name .. " and my id is " .. self.id)
	end
}

```

**Comment by well-in-that-case** [comment]
There's already a patch introduced for this type of function declaration, so this is likely something I can implement with minimal headache (but I could be wrong). As for properties, I will need to review the parser, but I imagine it can be done, but this may be redundant too since it plays no effect in the behavior of the table (you still create them with the create function). Not so sure about the struct keyword, appears redundant. After all, it's not a structure, it's just a table. And if I did implement it, it would just be skipped by the parser. So you could imagine.

But otherwise, suggestion seems nice. I'll keep ya posted.

**Comment by Frityet** [comment]
I was already working on an implementation on my fork, what is the function declaration you are talking about?

**Comment by well-in-that-case** [comment]
> I was already working on an implementation on my fork, what is the function declaration you are talking about?

http://lua-users.org/wiki/LuaPowerPatches
Ctrl + F "Function fields". Patched into Lua 5.2 already, so it may only need updating and credit.

Edit, link is down. Searched through the web server manually and got the file:
http://lua-users.org/files/wiki_insecure/jRhQ0hat/5.2/oofunc.diff

**Comment by Frityet** [comment]
The reason why I am making a new keyword is because the functionality it intends to abstract over is not just a table/function, it's also the setmetatable function calls, and the indexing. It would be ambiguous as just a table

**Comment by well-in-that-case** [comment]
Why would setmetatable be needed? And why would indexing need to change too?

**Comment by Frityet** [comment]
It is the [idomatic](https://www.lua.org/pil/16.html) way of doing this paradigm. I also want to add a "private" attribute that is only valid in the struct declaration  which would make it only available to methods in the struct. This would not make any sense outside of the struct declaration, and even in a regular table

**Comment by well-in-that-case** [comment]
That's about inheritance, which is fairly unrelated. Users can do this manually in their `create` function, or whatever they decide to call it. Private is __not__ possible.

**Comment by well-in-that-case** [comment]
Progress update,
https://github.com/well-in-that-case/Pluto/tree/0.3.0

**Comment by Frityet** [comment]
> Progress update,
> 
> https://github.com/well-in-that-case/Pluto/tree/0.3.0

Thank goodness, the lua parser was killing me

**Comment by well-in-that-case** [comment]
@Frityet https://pluto-lang.org/docs/New%20Features/Object-Oriented%20Programming

**Comment by Frityet** [comment]
> @Frityet [pluto-lang.org/docs/New%20Features/Object-Oriented%20Programming](https://pluto-lang.org/docs/New%20Features/Object-Oriented%20Programming)

Yep! I have been folliwng this project closely, looks great
