### ISSUE TITLE
Standard Library: requiredir

### ISSUE THREAD

**Issue by well-in-that-case** [PlutoLang/Pluto#502]
A version of require that performs said operation on each file within the provided directory. This has a bit of a different application because it'd be used on modules that modify the global environment instead of returning a table themselves, but it could possibly be tuned to support multiret.

The current solution of this is implemented by adding an `init.lua` or `init.pluto` file into the directory to load everything in one require call. But, this is boilerplate that we can consider eliminating.

**Comment by Sainan** [comment]
Like this kind of init.pluto?
```Lua
local function basename(path)
    return path:sub(#io.parent(path) + 2)
end

local function no_ext(path)
    return path:replace(".pluto", ""):replace(".lua", "")
end

local my_dir = io.parent(debug.getinfo(1, "S").short_src) -- path to folder that this file (init.pluto) resides in
local files = io.listdir(my_dir)
files = files:filter(|x| -> basename(x) != "init.pluto") -- exclude self
local subs = {}
for files as file do
    subs[no_ext(basename(file))] = dofile(file)
end
return subs
```

**Comment by well-in-that-case** [comment]
No, people usually just do this:

```lua
require("a")
require("b")
require("c")
```

And so on

**Comment by Sainan** [comment]
That really doesn't seem like a good code style. I'm not sure if we should offer any sort of help for that.
