### ISSUE TITLE
Require-and-assign shorthand

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#536]
I was thinking maybe `pluto_use crypto` as a shorthand for `local crypto = require "pluto:crypto"`, but idk if giving 'pluto_use' another meaning is a good idea.

**Comment by well-in-that-case** [comment]
People can always do `crypto = require("crypto")` to load it into their global environment and skip the "preloading" stuff for the rest of their files.

**Comment by Sainan** [comment]
Since we do have table destructuring, we could add a `*` module to preload, so users could do something like this:
```Lua
local { crypto } = require"pluto:*"
```
