### ISSUE TITLE
table.deduplicate(d)

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#554]
Removes duplicate values from a table

**Comment by well-in-that-case** [comment]
Seems like a niche enough operation for `filter` + another table to handle tbh

**Comment by Sainan** [comment]
Ehhh
```Lua
table.uniques = function(t)
    local seen = {}
    t:filter(function(x)
        if seen:contains(x) then return false end
        seen:insert(x)
        return true
    end)
    return t
end
```

**Comment by Sainan** [comment]
Although might need a different name such as table.deduplicate or table.dedup so we can have table.deduplicated or table.deduped for the copying variant.

**Comment by Sainan** [comment]
Somewhat worth noting that now this can be emulated as followed on 0.10.0:
```lua
local t = { "foo", "foo", "bar" }
print(dumpvar(t:countvalues():keys())) -- { "foo", "bar" }
```
Although probably still worthwhile to have its own function.
