### ISSUE TITLE
range

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#581]
Similar to Python's function of the same name, but inclusive range for match Lua's `for` semantics.
```Lua
function range(s, e, x = 1)
    if e == nil then
        assert(s ~= nil)
        e = s
        s = 1
    end
    local t = {}
    for i = s, e, x do
        t[#t + 1] = i
    end
    return t
end
```
This may seem a bit silly because it's just a for-loop's iterator expanded into a table, but it could be useful to generate quick test data, e.g. not having to spell out a range:
```Lua
local t = { 1, 2, 3, 4, 5, 6, 7, ... }
```
Similar to string.repeat.

**Comment by wolfoops** [comment]
What if e is a large number? 
This will consume a lot memory every call.

May it be made lazy with metatable?

btw, if it's lazy, range() may means an infinite array start from 1.
And a version range0(...) to start from 0,  so range0(5) is {0,1,2,3,4}?

**Comment by Sainan** [comment]
> What if e is a large number?
> This will consume a lot memory every call.

Well, yes, allocating a big table consumes a lot of memory. That's obviously not the intended use-case.

> May it be made lazy with metatable?

No, the intended use-case is to just get a trivial table.

> And a version range0(...) to start from 0, so range0(5) is {0,1,2,3,4}?

Given my proposed API, the way to get `{0,1,2,3,4}` would be `range(0, 4)`.

**Comment by wolfoops** [comment]
And a version range0(...) to start from 0, so range0(5) is {0,1,2,3,4}?

Given my proposed API, the way to get {0,1,2,3,4} would be range(0, 4).

> > And a version range0(...) to start from 0, so range0(5) is {0,1,2,3,4}?
> 
> Given my proposed API, the way to get `{0,1,2,3,4}` would be `range(0, 4)`.

Ah, you're right !
