### ISSUE TITLE
Update Soup vendor to latest commit to fix build for Android

### ISSUE THREAD

**Issue by asumbek** [PlutoLang/Pluto#598]
The Soup repository contains commit that fix building Soup on Android, the vendor should be update too.

**Comment by Sainan** [comment]
As far as I can tell, Pluto 0.8.0 builds fine on Android. I don't think changes made in Soup were related to issues observed in Pluto to begin with.

Mind you, as of recently, Soup is vendored with Pluto, so you do not build it independently, instead it is built with Pluto.
