### ISSUE TITLE
`make PLAT=linux` doesn't work on termux (terminal on android)

### ISSUE THREAD

**Issue by BlockOG** [PlutoLang/Pluto#61]
Mainly I asked for linux because android is basically linux, but apparently it still doesn't work

**Comment by BlockOG** [comment]
![Screenshot_2022-07-14-09-26-07-189_com termux](https://user-images.githubusercontent.com/68442822/178915209-b213dd5b-0958-4596-8fa6-a6234002e61b.png)
![Screenshot_2022-07-14-09-26-33-113_com termux](https://user-images.githubusercontent.com/68442822/178915222-bc1a4363-de55-4956-8cee-4ba7d6383ab5.png)
![Screenshot_2022-07-14-09-26-58-221_com termux](https://user-images.githubusercontent.com/68442822/178915229-417963da-dce2-4d9b-82c7-c180bd09b22b.png)

**Comment by ghost** [comment]
This looks like something that would be fixed by modifying the standard, but the Makefile already does that? Could you give me the output of `g++ -v`?

**Comment by Sainan** [comment]
Please try with the above commit.
```
git pull
git checkout origin/rename-ispow2
```

**Comment by BlockOG** [comment]
I'll try that tomorrow when I'll have time

**Comment by Sainan** [comment]
Did you forgor?

**Comment by BlockOG** [comment]
Yeah, I did forget then, but now it does work :D
