### ISSUE TITLE
More varargs in Assertion library

### ISSUE THREAD

**Issue by well-in-that-case** [PlutoLang/Pluto#632]
Some functions like istrue, less, etc, could support an infinite number of arguments and perform the comparison against all of the varargs.

This increases the elegance of the library in some instances, i.e who wants to chain a bunch of assert.istrue calls? You can do `a and b and c` but this will degrade the error information and won't tell you which variable was false. 

It comes with a cost: no ability to alert the user when they pass an unexpected amount of arguments, which was another thing I was considering. Primarily for us since it would detect accidental additions to the stack (like what just happened with the pipe operator). But this wouldn't be helpful for most scripters.

**Comment by Sainan** [comment]
I don't think this is a good idea because I might well do:
```Lua
local a = true
assert.istrue(a, b)
```
And how will it know 'b' was *supposed* to be true and not nil? -> You don't because you don't know how many arguments were passed.

**Comment by well-in-that-case** [comment]
> You don't because you don't know how many arguments were passed.

Varargs, not parameters. But yes, I agree, this seems to risk over-designing.
