### ISSUE TITLE
Shorthand table contains key syntax

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#64]
Given a table like this:
```Lua
local t = {
    ["a"] = true,
}
```
You can check if it contains a key like this:
```Lua
print(t["a"] ~= nil)
```
However, it would be cool to have a shorthand syntax like this:
```Lua
print("a" in t)
```
Although I'm not entirely sure if this is even possible.

**Comment by pjalsGit** [comment]
Pretty sure this would only save 3 bytes, but it does look like nicer syntax.
