### ISSUE TITLE
custom types / table types.

### ISSUE THREAD

**Issue by fsdfdfgdfghSD** [PlutoLang/Pluto#664]
## Custom types:
It should work like Luau, not that complex.

```lua
type A = int

local var: A = 5
```

## Custom table types
Again, it should be simple like Luau, or if you guys want to modify it but i'll give you an idea.

```lua
local Players: { [string]: {Kills: int, Deaths: int} } = {
    ["John"] = {
        Kills = 5
        Deaths = 5
    }
}
```

Players is a table with the key of a string and the value is a table which has inside of it "Kills" a int and "Deaths" an int again.

**Comment by Sainan** [comment]
I'm not too sure about the introduction of a new `type` keyword for basically no gain. It's been a consideration of mine to use existing tables/classes as a valid type-hint, but getting good coverage in regards to this stuff is though work with slow progress.

**Comment by fsdfdfgdfghSD** [comment]
I understand the type thing, but it wouldve been nice to be able to create custom types maybe a thing in which you can allow it using ```pluto_use``` exactly like `let` Also what does the type table mean? Just ```{}```?

**Comment by Sainan** [comment]
What exactly is the problem the `type` keyword would solve for you? Right now, the amount of types you can hint is pretty limited (see https://pluto-lang.org/docs/New%20Features/Type%20Hinting), and I don't think aliasing primitives is that interesting.

`{}` is an expression that evaluates to an empty table.

**Comment by fsdfdfgdfghSD** [comment]
Im asking what is the `table` type for type-hinting what does it mean an empty table?

**Comment by Sainan** [comment]
The table type in type hints refers to tables. `{}` is an empty table constructor.

**Comment by well-in-that-case** [comment]
LuaU's type system may look simple, but internally it's extremely complex and probably unattainable with Lua's native parser. Because we intend on retaining the ability to easily rebase on Lua — especially coming 5.5 — we cannot rewrite the parser like LuaU has.

@fsdfdfgdfghSD

**Comment by fsdfdfgdfghSD** [comment]
I understand, but i hope in the future the type-hinting future will become larger.
