### ISSUE TITLE
Named varargs in lambda function

### ISSUE THREAD

**Issue by fsdfdfgdfghSD** [PlutoLang/Pluto#670]
When trying to name your varargs and wrapping it into a lambda function it may cause an error that shouldn't and it's not even making sense, for example:

```lua
pluto_use const

const f = |...args| -> tonumber(args) + 1

print(f(1)) --> here: expected '|' to begin & terminate the lambda's paramater list.
```

But without named varargs it works as it should.

**Comment by Sainan** [comment]
Named varargs are currently not supported in lambdas.

**Comment by fsdfdfgdfghSD** [comment]
Oh lol i thought thats a bug, alright thanks.

**Comment by asumbek** [comment]
In meantime, you can pass `function(...args) return ... end` instead of using Lambda.
