### ISSUE TITLE
Type-hints in loops

### ISSUE THREAD

**Issue by fsdfdfgdfghSD** [PlutoLang/Pluto#674]
Allow us to use type-hints in loops as well for example:

```lua
for i: int = 1, 10 do
  print(i)
end
```

And also:

```lua
local T = {1, 2, 3}

for k: int, v: int in T do
  print(k, v)
end

for T as Int: int do
  print(Int)
end
```

While loops:

```lua
while true: bool do
  print("Hello World")
end
```

**Comment by Sainan** [comment]
You do realise how ludicrous this proposal is, right? `true: bool`... yeah, no shit.

What benefit do you hope to gain from this?

**Comment by fsdfdfgdfghSD** [comment]
Probably theres not really much benefit for the while one, but for the for one there is a benefit.

**Comment by Sainan** [comment]
For iteration, we don't have any insight as to what the iterator type is, so there would not be any benefit.
