### ISSUE TITLE
Can Pluto support to transform Pluto script to Lua 5.1 target? 

### ISSUE THREAD

**Issue by linux-china** [PlutoLang/Pluto#676]
Still lots of projects use LuaJIT and Lua locked to 5.1.  Can pluto work almost alike TypeScript(transform ts to js with target ES5)?   I can use Pluto to write scripts, and transform the scripts to Lua 5.1 target, then submit the "compiled" 5.1 scripts to LuaJit?

**Comment by well-in-that-case** [comment]
Pluto is a dialect based on Lua 5.4. As such, it generates Lua 5.4 bytecode — as long as you avoid the features marked for bytecode incompatibility — and retains the same bytecode backwards compatibility (or lack thereof) as normal PUC-Lua bytecode.

Lua 5.1 is old now though, and I doubt PUC-Lua 5.4 bytecode will often run flawlessly on a Lua 5.1 VM. If there is a tool that can translate 5.4 bytecode into being compatible with 5.1 bytecode, then technically this should be possible, but I don't know if such a tool exists.
