### ISSUE TITLE
Compile-Time Evaluation: Define

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#740]
As an alternative to the `const` statement, which is being deprecated in 0.9.0:

```lua
$define value = 69
print(value) --> 69
```

Although, it would have to imply `<constexpr>` instead of `<const>`.

Which makes me think that we could also deprecate `<constexpr>` in favor of this.

**Comment by well-in-that-case** [comment]
What's the point of this? It's just a renamed version of `<const>`, why would we deprecate `<const>` then add a fancier version of it?

**Comment by Sainan** [comment]
I'm not planning to deprecate `<const>` — that's a Lua feature.

**Comment by well-in-that-case** [comment]
My bad, of `const`

**Comment by Sainan** [comment]
I still think you slightly understood

**Comment by Sainan** [comment]
I still think you misunderstood the initial message here.

Basically, I do think `const` is a useful statement, but it's being hampered by being optional, hence being deprecated in 0.9.0. This proposed `$define` syntax would maintain the usefulness of it without having to be optional.

But the `$` would make this a feature of "compile-time evaluation", so it would need to have the same guarantees as Pluto's `<constexpr>` attribute, thus removing the need for it.
