### ISSUE TITLE
Optimize boolean massage

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#748]
This is a very minor thing, but when the user writes `!!x` (or `not not x`), currently, the generated code is just trivially doing the not operation twice, but it might be possible to generate more optimal code for this.

**Comment by well-in-that-case** [comment]
The compile-time concat optimization reinforced a lesson: these types of 'optimizations' have more to lose than gain and aren't worthwhile.

**Comment by Sainan** [comment]
I agree that this optimisation would be close-to-useless, although the compile-time concat definitely had a bit more reason for exisitng, and there's no reason for us to not re-add it at some point in the future, if we can do so without bugs.

Closing this because I can't think of a trivial way to implement this that would be provably bug-free.
