### ISSUE TITLE
Failed to compile v0.9.1 on aarch64 linux.

### ISSUE THREAD

**Issue by tqfx** [PlutoLang/Pluto#828]
See https://github.com/termux/termux-packages/issues/19856
```
error: undefined symbol: soup_intrin::aes_expand_key_128
error: undefined symbol: soup_intrin::aes_expand_key_192
error: undefined symbol: soup_intrin::aes_expand_key_256
```

**Comment by Sainan** [comment]
Fixed upstream: https://github.com/calamity-inc/Soup/commit/7cbfc6b04eb27d0bd35d1cf08bd97874b840754b

**Comment by Sainan** [comment]
Although we will probably release 0.9.2 soon, feel free to use https://github.com/PlutoLang/Pluto/commit/541426dea7c3e3c250c1ba23cb9f4d6801099161 as a patched 0.9.1 release.

**Comment by Sainan** [comment]
0.9.2 is now released.

**Comment by tqfx** [comment]
Thanks!
