### ISSUE TITLE
Lua header files cannot be included in a C project

### ISSUE THREAD

**Issue by Sculas** [PlutoLang/Pluto#844]
While Pluto cannot be compiled using a C compiler (since it's a C++ project), it does allow one to link it for C using `PLUTO_C_LINKAGE`.
However, the accompanying header files cannot be used because they're also C++. So then begs the question, **how to use Pluto in a C project?** For context, this isn't an *actual* C project, rather it's Go, but it only supports C interop (and thus, only C header files).

**Comment by Sainan** [comment]
It's the same ABI as Lua, so you would typically include lua.h, lualib.h, and lauxlib.h. When in doubt, grab these headers from the official Lua sources.
