### ISSUE TITLE
Single fallthrough not allowed

### ISSUE THREAD

**Issue by XmiliaH** [PlutoLang/Pluto#859]
Currently cases with just a fallthrough statement are not allowed which seems strage to me.

```lua
switch 1 do
    case 1:
        --[[@fallthrough]]
    case 2:
end
```

**Comment by Sainan** [comment]
I can't say if this was intended, but I'm also not sure of the merit of allowing the developer to write nonsensical annotations like this.

**Comment by XmiliaH** [comment]
I do not really care if it is or is not allowed, but I would not say that this is always a *nonsensical annotations*. Maybe there is a developer out there who has a special case in the switch statment that is empty and should fall trhough and mark this case as such to make it distinct, yet obvious.
