### ISSUE TITLE
segfault using string.dump and debug.getinfo

### ISSUE THREAD

**Issue by data-man** [PlutoLang/Pluto#863]
Source: https://groups.google.com/g/lua-l/c/wIzVAwNWTgM
```lua
sample = 'print("hello")'
stripped = load(string.dump(load(sample), true))
print(debug.getinfo(stripped, "L").activelines)
```

`$ pluto test.lua`

> Segmentation fault

**Comment by Sainan** [comment]
Given that this is an issue in upstream Lua, it will have to be fixed there, and then we will downstream the fix.
