### ISSUE TITLE
Allow PHP scripts to append compiler flags via argv

### ISSUE THREAD

**Issue by asumbek** [PlutoLang/Pluto#933]

**Comment by asumbek** [comment]
E.g
```bash
CXXFLAGS=" -Dsomething" php scripts/compile.php
LDFLAGS=" -fpermissive" php scripts/link_pluto.php
```

**Comment by Sainan** [comment]
LDFLAGS seems hacky; the scripts should always just work. CXXFLAGS for additional macro defines seems more reasonable.

**Comment by Sainan** [comment]
In regards to CXXFLAGS, can you not simply do `php scripts/compile.php "clang -DPLUTO_SOMETHING"`?

**Comment by asumbek** [comment]
> In regards to CXXFLAGS, can you not simply do `php scripts/compile.php "clang -DPLUTO_SOMETHING"`?

Nope, the PHP scripts passed that to `which`.
