### ISSUE TITLE
(crypto.sign) If extracting key from primes fails, you get an uninformative error.

### ISSUE THREAD

**Issue by aaronlink127** [PlutoLang/Pluto#962]
https://github.com/PlutoLang/Pluto/blob/be6a4ca0ce58a7582ffa268338e851890d1ae8be/src/lcryptolib.cpp#L645

If you give a key that cannot be derived properly to sign, and this line fails, it errors `pluto: (error message not a string)` back to the VM.

**Comment by Sainan** [comment]
I'm guessing it throws some C++ error in the underlying function.

**Comment by Sainan** [comment]
Steps to reproduce, which were so helpfully not provided:
```lua
local {bigint,crypto}=require"*"

require"crypto".sign("test", "rsa-sha1", {
	p = new bigint(10),
	q = new bigint(10)
})
```
More concerning, this actually seems to throw an access violation:
```lua
local {bigint,crypto}=require"*"

require"crypto".sign("test", "rsa-sha1", {
	p = new bigint(1),
	q = new bigint(1)
})
```
