### ISSUE TITLE
Unable to use C modules

### ISSUE THREAD

**Issue by Hedwig7s** [PlutoLang/Pluto#968]
I have tested 3 C modules: lua-zlib, lua-zip, luafilesystem (all on luarocks but manually compiling doesn't seem to fix)
All 3 throw the error "undefined symbol: lua_gettop"
My only guess considering that checking the symbols lua_gettop is there is that pluto using c++ is throwing off the c libraries
Using linux mint 22

**Comment by Sainan** [comment]
Well, these packages do seem to depend on Lua dynamic linking, so either throw them a liblua.so, or build Pluto with C ABI and hope that's a reasonable linking relationship that your OS can figure out.

**Comment by Hedwig7s** [comment]
Woah there slow down I feel like this should be something pluto can automatically handle it shouldn't require manual compilation with C ABI or somehow throwing them liblua.so

**Comment by Sainan** [comment]
And I feel like these modules should statically link for such trivial operations.

**Comment by Hedwig7s** [comment]
Most Lua C modules are dynamically linked

**Comment by Hedwig7s** [comment]
From my understanding this could likely be very easily fixed by making distribution builds build with a C ABI

**Comment by Sainan** [comment]
I don't think so, because these modules expect to link against something called "lua", but I'm also no Linux expert.

**Comment by Hedwig7s** [comment]
If you mean the lua header literally every single example module I found used that 
Could this at least be looked into to see if it can be fixed?

**Comment by Sainan** [comment]
I'm talking about the `-llua` linker flag in the Makefile.

**Comment by Hedwig7s** [comment]
Look I'm pretty sure this is how most Lua C modules work and Pluto already has C ABI support if this would fix it could it please be turned on for distribution?

**Comment by Sainan** [comment]
Have you tried if it does fix it? I'm typically on Windows, and on Windows, this would not actually make a difference. So, unless Linux proves different in this regard, you're asking for a placebo.

**Comment by Hedwig7s** [comment]
From what I can tell pluto builds automatically with the C ABI on windows which is likely why that isn't an issue
While I wasn't able to get the pluto binary to compile with the right ABI (I don't really do C) I was able to get libpluto to use the C ABI
Default:
`00000000000b8300 T _Z10lua_gettopP9lua_State` (mangled, what C sees)
`00000000000b8300 T lua_gettop(lua_State*)`
C ABI:
`00000000000a91b0 T lua_gettop` (in theory can be linked against by Lua C modules)

**Comment by Sainan** [comment]
"In theory" is great. Did you try it?

**Comment by Hedwig7s** [comment]
The pluto executable doesn't seem to expose any symbols so I'm not sure how to exactly

**Comment by Sainan** [comment]
Yeah, exactly. Executables having exports sounds like madness. I'm sure it's possible in theory, but I suggest you just install a Lua 5.4 distribution on your system so the liblua.so can be found by those modules.

**Comment by Hedwig7s** [comment]
The lua executable either does export the lua library or dynamically includes it

**Comment by Hedwig7s** [comment]
To be clear I have liblua installed and lua 5.4 works fine it's just pluto that fails
There is likely a change in pluto that makes it incompatible and my bet is it's ABI related

**Comment by Hedwig7s** [comment]
Look I've hit my knowledge limit I'd just like this issue reopened and this problem looked in to if possible
Complaining about how most lua libraries work won't fix the issue

**Comment by Sainan** [comment]
Okay, I've just tried this in a VM, and it seems that the expectation is indeed that the Lua executable itself exports these symbols.

**Comment by Hedwig7s** [comment]
Hang on I figured out a fix
Exporting LD_PRELOAD=path/to/libpluto.so (using C ABI) it no longer errors
If linked statically I do believe pluto must export the symbols, but dynamically with libpluto it needs to preload libpluto before any lua C modules (either way needs C ABI)

NOTE: Modifying LD_PRELOAD probably isn't the best idea within the program in case you're thinking of that I'm sure there's a better way

**Comment by Hedwig7s** [comment]
Thanks a ton
